#!/bin/bash

# Runs scripts to install the opengovernment.org site on a virtual machine
# These assume Ubuntu 10.10. 
# 
# For other Debian derivatives, modify the repository used by setup_mongodb, below.



# Make sure you use a mongodb repository that is appropriate for your current system.
# See http://www.mongodb.org/display/DOCS/Ubuntu+and+Debian+packages for official Mongodb packages
# Some samples:
# deb http://downloads.mongodb.org/distros/ubuntu 10.10 10gen
# deb http://downloads.mongodb.org/distros/ubuntu 10.4 10gen 
# deb http://downloads.mongodb.org/distros/ubuntu 9.10 10gen 
# deb http://downloads.mongodb.org/distros/debian 5.0 10gen 
# 
setup_mongodb()
{
# Check sources.list for mention of mongodb
  if ! grep mongodb /etc/apt/sources.list
    then
      echo $MONGOAPT >> /etc/apt/sources.list
      apt-get update
      apt-key adv --keyserver keyserver.ubuntu.com --recv 7F0CEB10
      apt-get -y install mongodb-stable
    fi
}

# Download geoserver from sourceforge, and put it into /var/lib/tomcat6/webapps
# Then update tomcat's config file 
setup_geoserver_ubuntu10()
{
  cd /var/lib/tomcat6/webapps

  # Fetch and unzip
  sudo -u tomcat6 wget 'http://downloads.sourceforge.net/geoserver/geoserver-2.0.2-war.zip'
  sudo -u tomcat6 unzip geoserver-2.0.2-war.zip && rm geoserver-2.0.2-war.zip

  # Update the /etc/default/tomcat6 config file
  # Use sed to change the config file's line containing JAVA_OPS. The resulting line wll be:
  # JAVA_OPS="-jvm server -Djava.awt.headless=true -Xmx256M"
  sed 's/^JAVA_OPS.*/JAVA_OPS="-jvm server -Djava.awt.headless=true -Xmx256M"/' /etc/default/tomcat6 > tmp.tmp
  rm -f /etc/default/tomcat6
  mv tmp.tmp /etc/default/tomcat6

  # Restart Tomcat
  service tomcat6 restart
}

# Packages. Lots of packages.
install_packages_ubuntu10()
{
	apt-get -y install build-essential bison openssl libreadline6 libreadline6-dev curl git 
	apt-get -y install zlib1g zlib1g-dev libssl-dev libyaml-dev libsqlite3-0 libsqlite3-dev sqlite3 libxml2-dev 
	apt-get -y install libxslt1-dev autoconf libc6-dev
	apt-get -y install libpq-dev libkdb5-4 postgresql-8.4 postgresql-doc-8.4
	apt-get -y install postgis postgresql-8.4-postgis
	apt-get -y install sphinxsearch
	apt-get -y install imagemagick
	apt-get -y install ruby-full rubygems
	apt-get -y install libffi-ruby
	apt-get -y install unzip
	apt-get -y install sudo
	apt-get -y install mongodb-stable
	apt-get -y install java-common default-jre-headless 
	apt-get -y install tomcat6
}


# now run the scripts
setup_mongodb
install_packages_ubuntu10
setup_geoserver_ubuntu10
