#!/bin/bash

# Start off with some checks ...

if [ -z $OPENGOVPARENTDIR ]
then
  # This script appears to be being run as a standalone script
  # So we have to set these variables ourselves
  OPENGOVPARENTDIR="/home/$USER"
  USERHOMEDIR="/home/$USER"
fi

ROOT_UID=0
E_NOREPODIR=65
E_WRONG_USER=66
E_NOREPO=67

if [ "$UID" -eq "$ROOT_UID" ]
then
  echo "This script must not be run as root." 
  exit $E_WRONG_USER
fi


# We need to know what repo to clone;
# The parent script, if any, will set GITREPO.
# Otherwise, if we're a standalone script, set it to $1.
if [ -z $GITREPO ]
then
  if [ -z "$1" ]
  then
    echo "Usage: $0 git-repo-to-clone"
    exit $E_NOREPO
  else
    GITREPO=$1
  fi
fi



# This function is needed to let rvm change its environment from
# within a script (like this one).
# If we don't run this before clone_site(), then clone_site()
# won't be able to use the command "rvm use ree@og".
# See http://rvm.beginrescueend.com/workflow/scripting/
load_rvm()
{
# Load RVM into a shell session *as a function*
if [[ -s "$HOME/.rvm/scripts/rvm" ]] ; then
  # First try to load from a user install
  source "$HOME/.rvm/scripts/rvm"
elif [[ -s "/usr/local/rvm/scripts/rvm" ]] ; then
  # Then try to load from a root install
  source "/usr/local/rvm/scripts/rvm"
else
  printf "ERROR: An RVM installation was not found.\n"
fi
}


# This function clones the git repository.
# You must run load_rvm before running this.
clone_site()
{
  load_rvm
  # cd to the parent of where we want to put the repository
  cd $OPENGOVPARENTDIR

  if [ ! -d opengovernment ]
  then
    echo "No repository directory. Cloning."
    # Clone!
    git clone $GITREPO
  else
    echo "Already found a repository, so not cloning again."
  fi

  if [ ! -d opengovernment ]
  then
    echo "Unable to find or clone repository. Exiting."
    exit $E_NOREPODIR
  fi

  # The new repo has a .rvmrc file. That's good! We like rvm.
  # But we need to move the .rvmrc file out of the way, so the 
  # user isn't prompted for input while this script runs.
  mv opengovernment/.rvmrc opengovernment/rvmrc
  cd opengovernment
  # Move it back.
  mv ./rvmrc ./.rvmrc

  git submodule init
  git submodule update
  rvm use ree-1.8.7
  rvm --create ree@og
  rvm use ree@og
  bundle install
}

# Then run those functions
clone_site

